
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";


export const metadata = {
  title: "Farmizo App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    
      <
      >
       <Navbar/> 
        {children}
       <Footer/>
      </>
    
  );
}
